#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x mailspring > /dev/null || mailspring --background &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x redshift > /dev/null || redshift &
pgrep -x dropbox > /dev/null || dropbox &
pgrep -x syncthing > /dev/null || syncthing &
pgrep -x feh > /dev/null || feh --bg-fill --randomize ~/Pictures/minimalistic-wallpaper-collection/ &
pgrep -x xsetroot > /dev/null || xsetroot -cursor_name left_ptr &
pgrep -x ~/.config/polybar/run.sh > /dev/null || ~/.config/polybar/run.sh &
pgrep -x check-battery > /dev/null || ~/.config/dunst/scripts/check-battery &
pgrep -x redshift -l 26.952500:75.710500 > /dev/null || redshift -l 26.952500:75.710500 &
pgrep -x check-battery > /dev/null || ~/.config/dunst/scripts/check-battery &
pgrep -x dropbox start > /dev/null || dropbox start &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config active_border_color         "#ebbcba"
bspc config focused_border_color         "#16233a"
bspc config normal_border_color         "#26233a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 -o desktop=7 state=floating follow=on
bspc rule -a Brave-browser desktop=1 tiled=off follow=on
bspc rule -a Spotify desktop=5 follow=on tiled=off
bspc rule -a Thunar -o state=floating
bspc rule -a mplayer2 -o state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey -o manage=off
